# Generated by Django 2.0.9 on 2025-01-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appvdseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField(max_length=200)),
                ('discount', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('bookcondition', models.CharField(max_length=100)),
                ('type', models.CharField(default=1, max_length=100)),
                ('availability', models.CharField(max_length=300)),
                ('numberofpages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=200)),
                ('BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField(max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('cmts', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=1000)),
                ('content_title', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=1000)),
                ('content_description', models.CharField(max_length=1000)),
                ('publication_date', models.CharField(max_length=100)),
                ('content_format', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='cust_thoughtwaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughtname', models.CharField(max_length=200)),
                ('content', models.CharField(default=1, max_length=20000)),
                ('category', models.CharField(default=1, max_length=20000)),
                ('publish_date', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=1, max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('age', models.CharField(default=1, max_length=200)),
                ('gender', models.CharField(default=1, max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('place', models.CharField(default=1, max_length=200)),
                ('post', models.CharField(default=1, max_length=200)),
                ('pin', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('orderstatus', models.CharField(max_length=200)),
                ('paymentstatus', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=200)),
                ('totalamount', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('place', models.CharField(default=1, max_length=200)),
                ('city', models.CharField(default=1, max_length=200)),
                ('state', models.CharField(default=1, max_length=200)),
                ('colony', models.CharField(default=1, max_length=200)),
                ('house', models.CharField(default=1, max_length=200)),
                ('pin', models.CharField(default=1, max_length=200)),
                ('deliverydate', models.CharField(max_length=200)),
                ('return_or_refund', models.CharField(max_length=200)),
                ('ordernotes', models.CharField(max_length=200)),
                ('ordercancellationreason', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cs1', to='eonapp.customer')),
                ('CUSTOMER_se', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cs2', to='eonapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.book')),
                ('CUSTOMER_ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer_order')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
                ('THOUGHTNAME', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.cust_thoughtwaves')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='online_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=1, max_length=200)),
                ('author', models.CharField(default=1, max_length=200)),
                ('description', models.CharField(blank=True, default=1, max_length=500)),
                ('book_format', models.CharField(default=1, max_length=500)),
                ('image', models.CharField(default=1, max_length=100)),
                ('filesize', models.CharField(default=1, max_length=100)),
                ('language', models.CharField(default=1, max_length=100)),
                ('no_ofpage', models.CharField(default=1, max_length=100)),
                ('upload_date', models.CharField(default=1, max_length=200)),
                ('type', models.CharField(default=1, max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default=1, max_length=3000)),
                ('emotion', models.CharField(default='Happy', max_length=1000)),
                ('GENRE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='onlinebk_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('revw', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
                ('ONLINE_BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.online_book')),
            ],
        ),
        migrations.CreateModel(
            name='order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(default=1, max_length=100)),
                ('option_b', models.CharField(default=1, max_length=100)),
                ('option_c', models.CharField(default=1, max_length=100)),
                ('option_d', models.CharField(default=1, max_length=100)),
                ('questions', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=1000)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
                ('ONLINE_BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.online_book')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rply', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
                ('ONLINE_BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.online_book')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('revw', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('BOOK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.book')),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('place', models.CharField(default=1, max_length=200)),
                ('post', models.CharField(default=1, max_length=100)),
                ('pincode', models.CharField(default=1, max_length=200)),
                ('certificate', models.CharField(default=1, max_length=150)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='seller_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=1, max_length=200)),
                ('orderstatus', models.CharField(default=1, max_length=200)),
                ('paymentstatus', models.CharField(default=1, max_length=200)),
                ('paymentmethod', models.CharField(default=1, max_length=200)),
                ('totalamount', models.CharField(default=1, max_length=200)),
                ('discount', models.CharField(default=1, max_length=200)),
                ('city', models.CharField(default=1, max_length=200)),
                ('state', models.CharField(default=1, max_length=200)),
                ('colony', models.CharField(default=1, max_length=200)),
                ('house', models.CharField(default=1, max_length=200)),
                ('pin', models.CharField(default=1, max_length=200)),
                ('deliverydate', models.CharField(default=1, max_length=200)),
                ('return_or_refund', models.CharField(default=1, max_length=200)),
                ('ordernotes', models.CharField(default=1, max_length=200)),
                ('customerfdbck', models.CharField(default=1, max_length=200)),
                ('ordercnclreason', models.CharField(default=1, max_length=200)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer')),
                ('SELLER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.seller')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.seller_order'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='SELLER_ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.seller_order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.login'),
        ),
        migrations.AddField(
            model_name='cust_thoughtwaves',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='THOUGHTNAME',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.cust_thoughtwaves'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='GENRE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.login'),
        ),
        migrations.AddField(
            model_name='appvdseller',
            name='SELLER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eonapp.seller'),
        ),
    ]
