# Generated by Django 2.0.9 on 2025-02-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
