# Generated by Django 2.0.9 on 2025-02-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0002_auto_20250222_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_thoughtwaves',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
