# Generated by Django 2.0.9 on 2025-02-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0004_auto_20250223_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='CATEGORY',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CUSTOMER',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ORDER',
        ),
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
