# Generated by Django 2.0.9 on 2025-02-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0005_auto_20250224_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='ordernotes',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='place',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='return_or_refund',
        ),
        migrations.RemoveField(
            model_name='seller_order',
            name='customerfdbck',
        ),
        migrations.RemoveField(
            model_name='seller_order',
            name='ordernotes',
        ),
        migrations.RemoveField(
            model_name='seller_order',
            name='return_or_refund',
        ),
    ]
