"""eon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from eonapp import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.log),
    path('login_post',views.login_post),
    path('admin_index',views.admin_index),
    path('chpass',views.chpass),
    path('chpass_post',views.chpass_post),
    path('add_cat',views.add_cat),
    path('addcat_post',views.addcat_post),
    path('edit_cat/<id>',views.edit_cat),
    path('editcat_post/<id>',views.editcat_post),
    path('delete_cat/<id>',views.delete_cat),
    path('view_cat',views.view_cat),
    path('seller_mngt',views.seller_mngt),
    path('sellerapprove/<id>',views.sellerapprove),
    path('rejectseller/<id>',views.rejectseller),
    path('seller_approval',views.seller_approval),
    path('blockuser/<id>',views.blockuser),
    path('blockeduser',views.blockeduser),
    path('unblockuser/<id>',views.unblockuser),
    path('reviw',views.reviw),
    path('dltreview/<id>',views.dltreview),
    # path('cust_tw',views.cust_tw),
    path('view_user',views.view_user),
    path('ordhist',views.ordhist),
    path('orderhist_post',views.orderhist_post),
    path('onlinebookadd',views.onlinebookadd),
    path('onlinebookadd_post',views.onlinebookadd_post),
    path('onlinebkview',views.onlinebkview),
    path('onlinebookedit/<id>',views.onlinebookedit),
    path('onlinebookedit_post/<id>',views.onlinebookedit_post),
    path('onlinebkdelete/<id>',views.onlinebkdelete),
    path('onlinebk_reviw',views.onlinebk_reviw),
    path('dlt_onlinebk_review/<id>',views.dlt_onlinebk_review),
    path('view_thoughtwaves/<id>',views.view_thoughtwaves),
    path('dlt_thoughtwave/<id>',views.dlt_thoughtwave),
    path('view_comment/<id>',views.view_comment),
    path('logout',views.logout),




    ####################################################################

    path('reg_seller',views.reg_seller),
    path('reg_seller_post',views.reg_seller_post),
    path('seller_view',views.seller_view),
    path('edit_profile_post/<id>',views.edit_profile_post),
    path('edit_profile/<id>',views.edit_profile),
    path('seller_chpass',views.seller_chpass),
    path('seller_chpass_post',views.seller_chpass_post),
    path('bookadd',views.bookadd),
    path('bookadd_post',views.bookadd_post),
    path('bookedit/<id>',views.bookedit),
    path('bookedit_post/<id>',views.bookedit_post),
    path('bkdelete/<id>',views.bkdelete),
    path('bkview/<id>',views.bkview),
    path('seller_index',views.seller_index),
    path('seller_view_order',views.seller_view_order),
    path('orderapprove/<id>',views.orderapprove),
    path('rejectorder/<id>',views.rejectorder),
    path('seller_order_sub/<id>',views.seller_order_sub),
    path('orderapproved',views.orderapproved),
    path('review_book/<id>',views.review_book),
    path('update_order_status/<id>',views.update_order_status),
    path('update_order_status_post/<id>',views.update_order_status_post),
    path('bkview_frontview',views.bkview_frontview),
    path('update_delivery_post/<id>/<status>',views.update_delivery_post),



    ############################################


    path('reg_cust',views.reg_cust),
    path('reg_cust_post',views.reg_cust_post),
    path('cust_index',views.cust_index),
    path('cust_view',views.cust_view),
    path('edit_csprofile/<id>',views.edit_csprofile),
    path('edit_csprofile_post/<id>',views.edit_csprofile_post),
    path('csbookadd',views.csbookadd),
    path('csbookadd_post',views.csbookadd_post),
    path('csbkview/<id>',views.csbkview),
    path('csbookedit/<id>',views.csbookedit),
    path('csbookedit_post/<id>', views.csbookedit_post),
    path('csbkdelete/<id>',views.csbkdelete),
    path('add_cart/<id>',views.add_cart),
    path('add_cart_post/<id>',views.add_cart_post),
    path('view_cart',views.view_cart),
    path('rmv_cart/<id>',views.rmv_cart),
    path('cs_order_view',views.cs_order_view),
    path('csorderapprove/<id>',views.csorderapprove),
    path('csrejectorder/<id>',views.csrejectorder),
    path('csorderapproved',views.csorderapproved),
    path('csupdate_status/<id>',views.csupdate_status),
    path('csupdate_status_post/<id>',views.csupdate_status_post),
    path('csupdate_delivery_post/<id>/<status>',views.csupdate_delivery_post),
    path('cs_order_sub/<id>',views.cs_order_sub),
    path('view_ordersed_books/<id>',views.view_ordersed_books),
    path('place_orderfrombook/<id>/<cslid>/<amt>',views.place_orderfrombook),
    path('place_orderfrombook_post/<id>/<cslid>/<amt>',views.place_orderfrombook_post),
    # path('csreview_book/<id>',views.csreview_book),
    path('place_orderfromcart/<id>/<cslid>/<type>/<amt>',views.place_orderfromcart),
    path('place_orderfromcart_post/<id>/<cslid>/<amt>',views.place_orderfromcart_post),
    path('cust_chpass',views.cust_chpass),
    path('cust_chpass_post',views.cust_chpass_post),
    path('view_customer_book/<id>',views.view_customer_book),
    path('view_seller_book/<id>', views.view_seller_book),

    # path('view_other_book_post',views.view_other_book_post),
    path('place_orderfrombookseller/<id>/<slid>/<amt>',views.place_orderfrombookseller),
    path('place_orderfrombookseller_post/<id>/<slid>/<amt>',views.place_orderfrombookseller_post),
    path('view_my_order',views.view_my_order),
    path('view_my_order_post',views.view_my_order_post),
    path('my_order_sub/<id>',views.my_order_sub),
    path('my_seller_order_sub/<id>',views.my_seller_order_sub),
    path('my_cust_order_cancel/<id>',views.my_cust_order_cancel),
    path('my_cust_order_cancel_post/<id>',views.my_cust_order_cancel_post),
    path('my_seller_order_cancel/<id>',views.my_seller_order_cancel),
    path('my_seller_order_cancel_post/<id>',views.my_seller_order_cancel_post),
    path('cs_onlinebkview/<id>', views.cs_onlinebkview),
    path('cs_onlinebkview_frontview_post', views.cs_onlinebkview_frontview_post),
    path('add_review/<id>',views.add_review),
    path('add_review_post/<id>',views.add_review_post),
    path('view_allreview/<id>',views.view_allreview),
    path('edit_review/<id>',views.edit_review),
    path('edit_review_post/<id>',views.edit_review_post),
    path('view_own_review',views.view_own_review),
    path('add_onlinebk_review/<id>',views.add_onlinebk_review),
    path('add_onlinebkreview_post/<id>', views.add_onlinebkreview_post),
    path('view_all_onlinebk_review/<id>', views.view_all_onlinebk_review),
    path('view_own_onlinebk_review', views.view_own_onlinebk_review),
    path('edit_onlinebk_review/<id>', views.edit_onlinebk_review),
    path('edit_onlinebk_review_post/<id>', views.edit_onlinebk_review_post),
    path('cs_dlt_review/<id>',views.cs_dlt_review),
    path('cs_dlt_onlinebk_review/<id>',views.cs_dlt_onlinebk_review),
    path('view_review_bout_mybk',views.view_review_bout_mybk),
    path('cs_academicbk_view/<id>',views.cs_academicbk_view),
    path('add_qtn/<id>',views.add_qtn),
    path('add_qtn_post/<id>',views.add_qtn_post),
    path('view_question/<id>',views.view_question),
    path('edit_question/<id>',views.edit_question),
    path('edit_question_post/<id>/<qid>', views.edit_question_post),
    path('view_mythoughtwaves/<id>',views.view_mythoughtwaves),
    path('add_mythoughtwaves',views.add_mythoughtwaves),
    path('add_mythoughtwaves_post',views.add_mythoughtwaves_post),
    path('edit_mythoughtwaves/<id>',views.edit_mythoughtwaves),
    path('edit_mythoughtwaves_post/<id>',views.edit_mythoughtwaves_post),
    path('delete_mythoughtwaves/<id>',views.delete_mythoughtwaves),
    path('delete_qtn/<id>',views.delete_qtn),
    path('all_thoughtwaves/<id>',views.all_thoughtwaves),
    path('add_comment/<id>',views.add_comment),
    path('add_comment_post/<id>',views.add_comment_post),
    path('delete_comment/<id>',views.delete_comment),
    path('tw_like/<id>',views.tw_like),
    path('attend_qtn/<id>',views.attend_qtn),
    path('attend_qtn_post/<id>',views.attend_qtn_post),
    path('score/<id>',views.score),
    path('cs_onlinebkview_post',views.cs_onlinebkview_post),
    path('chatbott',views.chatbott),
    path('chatsnd',views.chatsnd),
    path('chatrply', views.chatrply),
    path('studymaterial_frontview',views.studymaterial_frontview),
    path('studymaterial_frontview_post',views.studymaterial_frontview_post),
    path('payment/<id>/<amt>',views.payment),
    path('turn_pages/<c>',views.turn_pages),
    path('cs_onlinebkview_frontview',views.cs_onlinebkview_frontview),
    # path('emot_rec',views.emot_rec),
    path('onlinebkview_frontview',views.onlinebkview_frontview),
    path('onlinebkview_frontview_post',views.onlinebkview_frontview_post),
    path('onlinebkview/<id>',views.onlinebkview),
    path('csbkview_frontview',views.csbkview_frontview),
    path('view_customer_book_frontview',views.view_customer_book_frontview),
    path('view_seller_book_frontview', views.view_seller_book_frontview),
    path('csbkview_frontview_post',views.csbkview_frontview_post),
    path('bkview_frontview_post',views.bkview_frontview_post),
    path('mythoughtwave_frontview',views.mythoughtwave_frontview),
    path('allthoughtwave_frontview',views.allthoughtwave_frontview),
    path('view_allthoughtwave_frontview',views.view_allthoughtwave_frontview),
]